### ISSUE TITLE
Provide a simple "Get Started" in README.

### ISSUE THREAD

**Issue by pwalsh** [openspending/babbage#2]
@pudo are you up for it?

EG:

1. Install babbage in a venv
2. Steps to get a single CSV > model (e.g.: from ipython prompt)
4. Examples of querying the data just loaded from babbage

This would be **really** useful :).

**Comment by pudo** [comment]
Good point, will do!

**Comment by pudo** [comment]
Is this readable? I'll write up some docs on the HTTP API next: https://github.com/openspending/babbage#usage

**Comment by pwalsh** [comment]
@pudo yes good. even better if `procurement_model.json` was in the fixtures :).

**Comment by pwalsh** [comment]
THANKS.
