### ISSUE TITLE
Signs of success

### ISSUE THREAD

**Issue by longhotsummer** [openspending/babbage#23]
I had a meeting with the South African National Treasury yesterday and almost fell of my chair when a Treasury team member knew about babbage and what it was useful for. It was all thanks to the Open Spending work with Mexico.

Just wanted to let you guys know that the work you (and folks like @pudo) do has a wide impact. Very gratifying.

**Comment by pwalsh** [comment]
@longhotsummer that is great, thanks so much for the feedback!

Big kudos to @akariv @VictoriaVlad @cyberbikepunk and @DianaMPG who all worked really hard on the Mexico pilot!
