### ISSUE TITLE
Should babbage be able to create it's own tables?

### ISSUE THREAD

**Issue by pudo** [openspending/babbage#4]
Right now, this functionality is not in the babbage package, but rather in whatever host app uses it (e.g. cubepress, spendb). While I don't think that babbage should only be useable with tables that it has created itself, adding the necessary code to quickly generate a table (eg. from JTS) could make the package more convenient to use.

**Comment by pudo** [comment]
Alternatively, ``babbage`` could come to depent on [jts-sql](https://github.com/okfn/jts-sql) and the two might have some secret protocols for how to talk about star schema (#3).

**Comment by pwalsh** [comment]
`jts-sql` (which we'll update extensively, soon, BTW) would not suit here: in Fiscal Data Package, we want to go from mapping > DB tables, and not resources > DB tables.

Can you link to the relevant code in SpenDB? 

I like that babbage is agnostic to the creation of tables: not sue ATM what that means though: perhaps `babbage.fiscal-data-package` could be extended for the DB loading functionality.

**Comment by pudo** [comment]
The relevant code in ``spendb`` quite literally is ``jts-sql`` (that's where the lib comes from) :) This is because in ``spendb`` the tables generated are a function of the data uploaded, not the model applied - meaning users can change the model around afterwards without requiring the data to be re-loaded.

Of course this is less 'clean' than a normalized star schema approach, but it's the simplest thing and the best UX -- wondering if we can somehow retain the UX of model mutability even as we drag the aggregator towards a cleaner data model.

**Comment by pwalsh** [comment]
@pudo ( cc @akariv ) just thinking out loud, but in the FDP to babbage scenario, it seems we'd want a star schema, and that the tables created should be more or less ( :) ) consistent across all datasets. I think the table creation therefore possibly does belong with `babbage.fiscal-data-package`.

**Comment by pwalsh** [comment]
So, I think the answer is no, and we can close this issue. We are currently creating our own tables in the FDP - > babbage loader codebase. Maybe when that is done, we can all take a look. Perhaps there will be a reason to pull the table creation code out completely into a standalone lib.
